//go:build linux
// +build linux

// bpf_linux_stub.go provides the bpfObjects type and loadBpfObjects function
// for Linux builds where the real eBPF bytecode has NOT been generated yet.
//
// When you are ready to enable real eBPF runtime monitoring:
//
//  1. Install prerequisites on Linux:
//     sudo apt install clang llvm linux-headers-$(uname -r)
//
//  2. Install bpf2go:
//     go install github.com/cilium/ebpf/cmd/bpf2go@latest
//
//  3. Write your eBPF C program at internal/ebpf/bpf/execve_monitor.c
//     and add //go:generate go run github.com/cilium/ebpf/cmd/bpf2go bpf bpf/execve_monitor.c
//     to runtime.go, then run: go generate ./internal/ebpf/
//
//  4. Delete this file — the real generated bpf_bpfeb.go will replace it.

package ebpf

import (
	"fmt"

	ciliumebpf "github.com/cilium/ebpf"
)

// bpfObjects holds the eBPF programs and maps loaded into the kernel.
// In a real deployment this is generated by bpf2go from a C eBPF program.
type bpfObjects struct {
	TraceExecve *ciliumebpf.Program `ebpf:"trace_execve"`
	Events      *ciliumebpf.Map     `ebpf:"events"`
}

// Close releases all kernel resources held by the eBPF objects.
func (o *bpfObjects) Close() {
	if o.TraceExecve != nil {
		o.TraceExecve.Close()
	}
	if o.Events != nil {
		o.Events.Close()
	}
}

// loadBpfObjects is a stub that returns an error guiding the user to compile
// the real eBPF bytecode. Replace this file with the bpf2go-generated output
// to enable actual runtime monitoring.
func loadBpfObjects(obj *bpfObjects, opts *ciliumebpf.CollectionOptions) error {
	return fmt.Errorf(
		"eBPF bytecode not compiled — runtime monitoring disabled.\n" +
			"To enable it: install clang + linux-headers, write bpf/execve_monitor.c,\n" +
			"then run: go generate ./internal/ebpf/\n" +
			"See internal/ebpf/bpf_bpfeb.go for full instructions.",
	)
}
