// bpf_bpfeb.go is a placeholder for the compiled eBPF bytecode.
// In a real deployment, this file is generated by running:
//
//	go generate ./internal/ebpf/
//
// Which invokes bpf2go to compile the C eBPF program (bpf/execve_monitor.c)
// into Go-embeddable bytecode for both little-endian (bpfel) and big-endian (bpfeb) targets.
//
// Prerequisites for generation (Linux only):
//   - clang 14+
//   - linux-headers or BTF-enabled kernel
//   - github.com/cilium/ebpf/cmd/bpf2go

//go:build ignore
// +build ignore

package ebpf

// bpfObjects contains maps and programs after loading the eBPF objects.
// This is normally auto-generated by bpf2go. Defined here as a placeholder
// so the package compiles on all platforms.
type bpfObjects struct {
	TraceExecve interface{} // *ebpf.Program
	Events      interface{} // *ebpf.Map (ringbuf)
}

func (o *bpfObjects) Close() {}

func loadBpfObjects(obj *bpfObjects, opts interface{}) error { return nil }
